doc: add initial CODEOWNERS and MAINTAINERS
notaryproject/notation-hashicorp-vault pull request #2
Opened 2023-05-16 13:33 UTC by FeynmanZhou

Add initial CODEOWNERS and MAINTAINERS per discussion in https://github.com/notaryproject/.github/issues/26. I hope @notaryproject/notaryproject-governance-maintainers @notaryproject/notaryproject-org-maintainers could help to review and approve this PR. Thanks!

2023-05-16 16:00 UTC, toddysm requested changes

2023-05-16 16:00 UTC, toddysm commented on MAINTAINERS
> +Patrick Zheng <patrickzheng@microsoft.com> (@patrickzheng200)
This user doesn't match the CODEOWNERS entry. Also the new handle is @Two-Hearts

2023-05-17 00:55 UTC, Two-Hearts commented on CODEOWNERS
> +* @cipherboy @OliverShang @priteshbandi @shizhMSFT
Hi @FeynmanZhou, should I be added into this list?

2023-05-17 09:24 UTC, Two-Hearts approved these changes
LGTM

2023-05-22 19:04 UTC, toddysm approved these changes

2023-05-22 19:44 UTC, cipherboy approved these changes
Not sure if I'm supposed to ACK this or not, but my details look good and as I've mentioned to Feynman in a mail, happy to help review designs and code to the project!

2023-05-23 01:09 UTC, priteshbandi approved these changes
LGTM

2023-05-30 06:08 UTC, shizhMSFT approved these changes
LGTM

2023-05-30 06:09 UTC, merged